import { execSync } from 'child_process'
import fs from 'fs'
import os from 'os'
import path from 'path'

export const runtime = 'nodejs'

export async function POST(request: Request) {
  const { workDir, projectName } = (await request.json()) as {
    workDir: string
    projectName: string
  }

  if (!workDir || !fs.existsSync(workDir)) {
    return Response.json({ error: 'workDir not found' }, { status: 400 })
  }

  // Auto-generate README if missing
  const readmePath = path.join(workDir, 'README.md')
  if (!fs.existsSync(readmePath)) {
    const readme = [
      `# ${projectName}`,
      '',
      'Generated by [ArchViber](https://github.com/URaux/arch-viber)',
      '',
      '## Getting Started',
      '',
      '```bash',
      'npm install',
      'npm run dev',
      '```',
      '',
      `Generated at: ${new Date().toISOString()}`,
    ].join('\n')
    fs.writeFileSync(readmePath, readme, 'utf-8')
  }

  const safeName =
    (projectName?.replace(/[^a-zA-Z0-9\u4e00-\u9fff-]/g, '-') || 'project').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'project'

  // Write zip to OS temp dir to avoid polluting workDir parent
  const zipPath = path.join(os.tmpdir(), `${safeName}-${Date.now()}.zip`)

  try {
    execSync(
      `powershell -Command "Compress-Archive -Path '${workDir}\\*' -DestinationPath '${zipPath}' -Force"`,
      { timeout: 30000 }
    )
  } catch {
    return Response.json({ error: 'Failed to create archive' }, { status: 500 })
  }

  let zipBuffer: Buffer
  try {
    zipBuffer = fs.readFileSync(zipPath)
  } finally {
    try { fs.unlinkSync(zipPath) } catch { /* ignore */ }
  }

  return new Response(new Uint8Array(zipBuffer), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeName}.zip"`,
    },
  })
}
