#!/usr/bin/env node
/**
 * policy-init.mjs — scaffolds .archviber/policy.yaml interactively.
 *
 * Usage:
 *   node scripts/policy-init.mjs          # 5-question wizard
 *   node scripts/policy-init.mjs --yes    # write permissive defaults silently
 *   node scripts/policy-init.mjs --force  # overwrite existing policy.yaml
 */

import { createInterface } from 'node:readline'
import { existsSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = process.cwd()
const archviberDir = join(repoRoot, '.archviber')
// Fall back to script-adjacent example if not found in cwd
const examplePath = existsSync(join(archviberDir, 'policy.example.yaml'))
  ? join(archviberDir, 'policy.example.yaml')
  : join(__dirname, '..', '.archviber', 'policy.example.yaml')
const targetPath = join(archviberDir, 'policy.yaml')

const args = process.argv.slice(2)
const YES = args.includes('--yes')
const FORCE = args.includes('--force')

function bail(msg) {
  process.stderr.write(msg + '\n')
  process.exit(1)
}

if (existsSync(targetPath) && !FORCE) {
  bail(
    `policy.yaml already exists at ${targetPath}.\nRun with --force to overwrite.`,
  )
}

if (!existsSync(examplePath)) {
  bail(`policy.example.yaml not found at ${examplePath}.`)
}

mkdirSync(archviberDir, { recursive: true })

if (YES) {
  copyFileSync(examplePath, targetPath)
  process.stdout.write(`Created permissive policy.yaml at ${targetPath}\n`)
  process.exit(0)
}

// Interactive wizard
const rl = createInterface({ input: process.stdin, output: process.stdout })

function ask(question) {
  return new Promise((resolve) => rl.question(question, resolve))
}

function yesNo(answer, defaultVal = false) {
  const s = answer.trim().toLowerCase()
  if (s === 'y' || s === 'yes') return true
  if (s === 'n' || s === 'no') return false
  return defaultVal
}

function optInt(answer) {
  const n = parseInt(answer.trim(), 10)
  return Number.isFinite(n) && n >= 0 ? n : undefined
}

async function wizard() {
  process.stdout.write('\nArchViber policy.yaml wizard (5 questions)\n\n')

  const failOnRemoved = yesNo(
    await ask('Fail PR on ANY removed block? [y/N]: '),
    false,
  )
  const failOnAdded = yesNo(
    await ask('Fail PR on ANY added block? [y/N]: '),
    false,
  )
  const failOnChanged = yesNo(
    await ask('Fail PR on ANY changed block (rename/container/anchor)? [y/N]: '),
    false,
  )

  const maxRemovedRaw = await ask(
    'Max removed blocks before failing (leave blank = no limit): ',
  )
  const maxAddedRaw = await ask(
    'Max added blocks before failing (leave blank = no limit): ',
  )

  rl.close()

  const maxRemovedBlocks = optInt(maxRemovedRaw)
  const maxAddedBlocks = optInt(maxAddedRaw)

  const lines = [
    '# Generated by scripts/policy-init.mjs',
    'drift:',
    `  failOnRemoved: ${failOnRemoved}`,
    `  failOnAdded: ${failOnAdded}`,
    `  failOnChanged: ${failOnChanged}`,
    '  failOnRemovedContainers: false',
    '  failOnRemovedEdges: false',
  ]
  if (maxRemovedBlocks !== undefined) lines.push(`  maxRemovedBlocks: ${maxRemovedBlocks}`)
  if (maxAddedBlocks !== undefined) lines.push(`  maxAddedBlocks: ${maxAddedBlocks}`)

  writeFileSync(targetPath, lines.join('\n') + '\n')
  process.stdout.write(`\nCreated ${targetPath}\n`)
}

wizard().catch((err) => {
  process.stderr.write(String(err) + '\n')
  process.exit(1)
})
